'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ko' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('ko');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (savedLang === 'ko' || savedLang === 'en')) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const translations: Record<Language, Record<string, string>> = {
  ko: {
    // Landing
    'landing.title': 'WORKLESS',
    'landing.subtitle': '비정형 애자일 워크스페이스',
    'landing.mainText': '당신의 액션을 위하여!',
    'landing.feature1.title': 'AI와 서비스 연동',
    'landing.feature1.gmail.title': 'Gmail 연동',
    'landing.feature1.gmail.desc': '"Workless" 라벨 이메일을 자동으로 메모 카드화하여 기록',
    'landing.feature1.ai.title': 'AI 어시스턴트',
    'landing.feature1.ai.desc': '기록한 내용의 맥락을 이해하고 인사이트, 액션아이템 제안, 연관 정보 자동 연결',
    'landing.feature2.title': '핵심 기능',
    'landing.feature2.canvas.title': '무한 캔버스 화이트보드',
    'landing.feature2.canvas.desc': '끝없는 2D 공간에서 자유롭게 아이디어를 메모하고, 브레인스토밍하며, 체계적으로 정리할 수 있는 생산성 도구',
    'landing.feature3.title': 'AI 페르소나 커스터마이징',
    'landing.feature3.desc': '업무 스타일에 맞는 AI 어시스턴트를 만들어보세요. 친근한 코치부터 전문적인 컨설턴트, 창의적인 파트너까지 - 당신만의 맞춤형 AI 협업 도구로 생산성을 극대화하세요.',
    'landing.feature4.title': '위젯 & 시각화',
    'landing.feature4.widgets.title': '다양한 위젯 도구',
    'landing.feature4.widgets.desc': '캘린더, 문서 뷰어, 할일 관리, 미니맵 등 실용적인 위젯으로 화이트보드를 업무용 협업 공간으로 확장',
    'landing.feature4.viz.title': '지식 맥락 시각화',
    'landing.feature4.viz.desc': '태그로 연결된 메모와 아이디어가 자동으로 그룹화되며, 공간적 배치를 통해 생각의 흐름과 연관 관계를 직관적으로 파악',
    'landing.start': '시작하기',
    'landing.agree': '서비스 약관 및 개인정보처리방침에 동의합니다',
    'landing.terms': '서비스 약관',
    'landing.privacy': '개인정보처리방침',
    'landing.gmail.title': 'Gmail 데이터 사용:',
    'landing.gmail.desc': '"Workless" 라벨이 지정된 이메일만 읽기 전용으로 접근하며, 이메일을 메모로 변환하는 데만 사용됩니다. 이메일을 보내거나 수정하지 않습니다.',
    'landing.privacy.title': '개인정보 보호:',
    'landing.privacy.desc': '수집된 데이터는 서비스 제공 목적으로만 사용되며 제3자에게 판매하지 않습니다.',
    'landing.contact': '문의하기',

    // Gmail Import
    'gmail.import.title': 'Gmail 메일 선택',
    'gmail.import.desc': '가져올 메일을 선택해주세요 (라벨: Workless)',
    'gmail.import.empty': '가져올 수 있는 메일이 없습니다.',
    'gmail.import.alreadyImported': '이미 추가됨',
    'gmail.import.button.cancel': '취소',
    'gmail.import.button.import': '{count}개 메일 가져오기',
    'gmail.import.toast.analyzing': '메일을 분석하고 있어요',
    'gmail.import.toast.converting': 'AI가 기록으로 변환 중입니다...',
    'gmail.import.noNewMail': '새 메일 없음',
    'gmail.import.checking': '확인 중...',
    'gmail.import.importing': '가져오는 중...',
    'gmail.import.selecting': '선택 중...',
    'gmail.import.failed': '실패',

    // Onboarding
    'onboarding.note': '메모 작성',
    'onboarding.note.desc1': '• 파일 첨부 가능',
    'onboarding.note.desc2': '• @태그로 참조',
    'onboarding.connect': '카드 연결',
    'onboarding.connect.desc1': '• 카드끼리 선으로 연결',
    'onboarding.connect.desc2': '• AI가 자동으로 그룹 제안',
    'onboarding.tag': '태그 & 분류',
    'onboarding.tag.desc1': '• 태그 자동 분류',
    'onboarding.tag.desc2': '• 시간 맥락 추적',
    'onboarding.action': '시작하기',
    'onboarding.progress': '진행률',
    'onboarding.todo1': '카드 3개 만들기',
    'onboarding.todo2': '카드끼리 연결하기',
    'onboarding.todo3': 'AI 기능 사용해보기',
    'onboarding.calendar': '캘린더',
    'onboarding.preview': '미리보기',
    'onboarding.justNow': '방금 전',
    'onboarding.tutorial': '튜토리얼',
    'onboarding.feature': '기능',

    // Dashboard
    'dashboard.title': 'Workless',
    'dashboard.subtitle': '사고의 흐름을 보는 비정형 워크스페이스',
    'dashboard.menu.groups': '그룹 관리',
    'dashboard.menu.memories': '기억 관리',
    'dashboard.menu.settings': '설정',
    'dashboard.auth.logout': '로그아웃',
    'dashboard.auth.login': '로그인',
    'dashboard.loading.workspace': '워크스페이스 로딩 중...',
    'dashboard.loading.redirecting': '로그인 페이지로 이동 중...',
    'dashboard.loading.fetching': '불러오는 중...',
    'dashboard.insights.show': '인사이트 보기',
    'dashboard.insights.hide': '인사이트 숨기기',
    'dashboard.modal.groups.title': '그룹 관리',
    'dashboard.modal.query.title': '물어보기',

    // MemoryListPanel
    'memory.list.title': '기억 관리',
    'memory.list.tab.all': '전체 ({count})',
    'memory.list.tab.memory': '기억 ({count})',
    'memory.list.tab.widget': '위젯 ({count})',
    'memory.list.search.placeholder': '검색...',
    'memory.list.noResult': '항목이 없습니다',
    'memory.list.item.noTitle': '제목 없음',
    'memory.list.project.title': '액션 프로젝트',
    'memory.list.project.estimated': '예상: {duration}',
    'project.draft.button': '초안',
    'project.draft.generating': '생성 중...',

    // MemoryView
    'memory.view.button.board': '보드로 이동',
    'memory.view.mode.board': '보드 뷰',
    'memory.view.mode.list': '목록 뷰',
    'memory.view.recent': '최근 기억',
    'memory.view.noMemory': '아직 저장된 기억이 없습니다. 아래 입력창에 첫 번째 생각을 기록해보세요!',
    'memory.view.zoom': '확대/축소',
    'memory.view.loading': '불러오는 중...',
    'memory.view.ai.analyzing': 'AI가 그룹을 분석하고 있어요...',
    'memory.view.ai.failed': '그룹 설명을 불러올 수 없습니다.',
    'memory.view.board.title': '화이트보드',
    'memory.view.board.restore': '이전 배열로',
    'memory.view.board.restore.title': '이전 배열로 되돌리기',
    'memory.view.board.arrange': '맞춤 배열',
    'memory.view.board.arrange.title': '연결선 기반으로 자동 배열',
    'memory.view.board.arranging': '배열 중...',
    'memory.view.board.import.gmail': 'Gmail 가져오기',
    'memory.view.board.import.gmail.success': 'Gmail에서 {count}개의 이메일을 가져왔습니다.',
    'memory.view.board.widget.add': '위젯 추가',
    'memory.view.board.widget.menu': '위젯 모음',
    'memory.view.board.widget.synergy': '위젯 시너지',
    'memory.view.board.group.manage': '그룹 관리',
    'memory.view.board.group': '그룹',
    'memory.view.board.flag.manage': '깃발 관리',
    'memory.view.board.flag': '깃발',
    'memory.view.board.zoom.reset': '초기화',
    'memory.view.board.widget.minimap': '미니맵',
    'memory.view.board.widget.viewer': '뷰어',
    'memory.view.board.widget.recorder': '레코더',
    'memory.view.board.widget.db': 'DB',
    'memory.view.board.widget.actionPlan': '액션플랜',
    'memory.view.board.widget.blob': 'Blob',
    'memory.view.board.widget.blob.on': 'Blob ON',
    'memory.view.board.widget.minimap.limit': '미니맵은 보드당 하나만 추가할 수 있습니다',
    'memory.view.board.widget.actionPlan.select': '기억들을 선택한 후 프로젝트를 생성하세요',

    // Calendar
    'calendar.title': '캘린더',
    'calendar.view.month': '월',
    'calendar.view.week': '주',
    'calendar.view.day': '일',
    'calendar.view.week.empty': '주 뷰는 곧 추가될 예정입니다',
    'calendar.record.count': '{count}개의 기록',
    'calendar.todo.count': '{count}개의 할일',
    'calendar.todo.title': '일정',
    'calendar.todo.add': '+ 추가',
    'calendar.todo.placeholder': '일정 입력... (@로 기록 태그)',
    'calendar.todo.none': '일정이 없습니다',
    'calendar.memory.title': '기록',
    'calendar.memory.none': '이 날 기록이 없습니다',
    'calendar.back': '뒤로',
    'calendar.format.month': 'yyyy년 M월',
    'calendar.format.day': 'yyyy년 M월 d일 (E)',

    // InsightsPanel
    'insights.title': '데일리 정리 시간',
    'insights.desc': '오늘 하루를 돌아보고\n내일을 준비해요',
    'insights.refresh': '새로고침',
    'insights.summary.title': '요약',
    'insights.goals.title': '🎯 진행 중인 목표',
    'insights.goals.progress': '진행률',
    'insights.goals.completed': '{completed}/{total} 단계 완료',
    'insights.topics.title': '주요 주제',
    'insights.topics.count': '{count}개',
    'insights.suggestions.title': '제안',
    'insights.loading': '분석 중...',
    'insights.error': '인사이트를 불러올 수 없습니다',
    'insights.error.title': '오류',
    'insights.error.retry': '다시 시도',
    'insights.goal.category.idea': '아이디어',
    'insights.goal.category.request': '요청',
    'insights.goal.category.habit': '습관',
    'insights.goal.modal.desc': '📝 목표 설명',
    'insights.goal.modal.plan': '실행 계획',
    'insights.goal.modal.progress': '전체 진행률',
    'insights.goal.modal.created': '{date} 생성',
    'insights.goal.action.archive': '보관',
    'insights.goal.action.delete': '삭제',
    'insights.goal.action.save': '저장',
    'insights.goal.action.saving': '저장 중...',
    'insights.goal.toast.updated': '✅ 목표가 업데이트되었습니다!',
    'insights.goal.toast.deleted': '✅ 목표가 삭제되었습니다!',
    'insights.goal.toast.archived': '✅ 목표가 보관되었습니다!',
    'insights.goal.toast.updateFailed': '업데이트 실패',
    'insights.goal.toast.updateError': '업데이트 중 오류 발생',
    'insights.goal.toast.archiveFailed': '보관 실패',
    'insights.goal.toast.archiveError': '보관 중 오류 발생',

    // Settings
    'settings.title': '데이터 및 동기화 설정',
    'settings.desc': 'Workless는 데이터를 브라우저에 우선 저장하여 오프라인에서도 작동합니다.',
    'settings.status.title': '시스템 상태',
    'settings.status.network': '네트워크 상태',
    'settings.status.online': '온라인 연결됨',
    'settings.status.offline': '오프라인 상태',
    'settings.status.syncMode': '현재 동기화 모드',
    'settings.status.syncMode.disabled': '클라우드 동기화 비활성',
    'settings.status.syncMode.enabled': '수동 동기화 대기',
    'settings.status.syncMode.auto': '자동 실시간 동기화',
    'settings.status.lastSync': '최근 동기화 시점',
    'settings.status.needsSync': '서버와 동기화되지 않은 데이터가 있습니다.',
    'settings.status.stats.title': '내 기기에 저장된 데이터 통계',
    'settings.status.stats.memories': '메모리',
    'settings.status.stats.groups': '그룹',
    'settings.status.stats.goals': '목표',
    'settings.status.stats.widgets': '위젯',
    'settings.sync.title': '동기화 옵션',
    'settings.sync.disabled.title': '클라우드 비활성 (로컬 전용)',
    'settings.sync.disabled.desc': '어떠한 데이터도 서버에 전송하지 않습니다. 사생활이 완벽히 보호되지만, 다른 기기에서 데이터를 볼 수 없습니다.',
    'settings.sync.manual.title': '수동 백업 모드',
    'settings.sync.manual.desc': '데이터가 내 기기에만 머물며, 원할 때만 아래 \'지금 동기화\' 버튼을 통해 서버에 백업합니다.',
    'settings.sync.auto.title': '실시간 동기화 (권장)',
    'settings.sync.auto.desc': '데이터가 변경될 때마다 서버와 자동으로 동기화됩니다. 모바일이나 다른 컴퓨터에서도 동일한 내용을 즉시 확인할 수 있습니다.',
    'settings.sync.encryption.title': '엔드-투-엔드 암호화 적용',
    'settings.sync.encryption.desc': '서버로 전송되는 데이터는 AES-256 방식으로 암호화되어 보관됩니다. 귀하의 계정 비밀번호를 기반으로 생성된 키 없이는 누구도 내용을 열람할 수 없습니다.',
    'settings.sync.button.backup': '지금 서버로 백업',
    'settings.sync.button.backup.progress': '동기화 진행 중...',
    'settings.sync.button.restore': '서버 데이터로 복원',
    'settings.sync.button.diagnose': '로컬 데이터 진단하기',
    'settings.sync.button.forceRestore': '데이터가 안 보이나요? 서버에서 강제 복원하기',
    'settings.export.title': '데이터 내보내기 및 가져오기',
    'settings.export.section.title': '내보내기 (Export)',
    'settings.export.section.desc': '현재 브라우저에 저장된 모든 정보를 JSON 파일로 다운로드합니다. 백업 파일을 직접 관리하고 싶을 때 사용하세요.',
    'settings.export.button': '📥 데이터 파일 다운로드',
    'settings.import.section.title': '가져오기 (Import)',
    'settings.import.section.desc': '이전에 내보낸 JSON 파일을 불러옵니다.',
    'settings.import.placeholder': 'JSON 파일을 선택하거나 여기로 드래그',
    'settings.import.button.overwrite': '전체 덮어쓰기',
    'settings.import.button.merge': '기존 데이터와 병합',
    'settings.info.title': '로컬 우선(Local-First) 기술 안내',
    'settings.info.1': '귀하의 데이터는 브라우저 내 IndexedDB라는 안전한 저장소에 1순위로 기록됩니다.',
    'settings.info.2': '네트워크 연결이 끊겨도 메모 추가 및 조회 등 모든 기능을 평소처럼 이용할 수 있습니다.',
    'settings.info.3': '서버 동기화는 데이터 백업 및 멀티 디바이스 환경을 위한 선택 사항입니다.',
    'settings.info.4': '"당신의 데이터는 당신의 기기에 머물러야 한다"는 철학을 준수합니다.',
    'settings.button.back': '대시보드로 돌아가기',
    'settings.auth.required': '로그인이 필요합니다.',
    'settings.auth.button': '로그인하러 가기',

    // QueryPanel
    'query.placeholder': '예: 요즘 내가 무슨 생각 많이 했어?',
    'query.button.ask': '물어보기',
    'query.button.thinking': '생각 중...',
    'query.quick.1': '요즘 내가 무슨 생각 많이 했어?',
    'query.quick.2': '아이디어 관련해서 뭐 쌓여 있어?',
    'query.quick.3': '업무 관련 기록 보여줘',
    'query.quick.4': '최근 회의록 요약해줘',
    'query.result.summary': '요약',
    'query.result.related': '관련 기억 ({count}개)',
    'query.result.suggestions': '제안',
    'query.error.failed': '요약 생성에 실패했습니다',

    // Auth
    'auth.signin.title': 'WORKLESS',
    'auth.signin.subtitle': '맥락을 구체화. 비정형 애자일 워크스페이스',
    'auth.signin.desc': '구글 계정으로 로그인하여 시작하세요',
    'auth.signin.button': 'Google로 로그인',
    'auth.signin.guide.title': '이렇게 사용해요 👇',
    'auth.signin.guide.desc': '로그인하면 바로 시작할 수 있어요',
    'auth.signin.alert.terms': '약관 동의가 필요합니다.',

    // GlobalSearch
    'search.placeholder': '/ 를 눌러 기억 검색...',
    'search.guide.move': '이동',
    'search.guide.select': '선택',
    'search.guide.close': '닫기',
    'search.noResult': '검색 결과가 없습니다',

    // Flag Management
    'flag.manage.add': '깃발 추가',
    'flag.manage.placing': '📍 보드에 클릭하여 깃발을 배치하세요 (ESC: 취소)',
    'flag.manage.noFlags': '깃발을 추가하여 중요한 위치를 북마크하세요',

    // Group Management
    'group.manage.all': '전체',
    'group.manage.title': '그룹 관리',
    'group.manage.desc': '비슷한 기억들을 묶어서 관리하세요',
    'group.manage.button.ai': 'AI로 묶기',
    'group.manage.button.create': '직접 만들기',
    'group.manage.noGroups': '아직 그룹이 없습니다',
    'group.manage.ai.title': 'AI 그룹 제안',
    'group.manage.ai.accept': '생성',
    'group.manage.modal.create.title': '새 그룹 만들기',
    'group.manage.modal.create.name': '그룹 이름',
    'group.manage.modal.create.name.placeholder': '예: 프로젝트 아이디어',
    'group.manage.modal.create.color': '색상',
    'group.manage.modal.create.memories': '기억 선택 ({count}개)',
    'group.manage.modal.create.button.create': '생성',
    'group.manage.toast.ai.analyzing': 'AI가 그룹을 분석하고 있어요...',
    'group.manage.toast.ai.failed': 'AI 제안을 불러오는데 실패했습니다',
    'group.manage.delete.confirm': '이 그룹을 삭제하시겠습니까?',
    'group.manage.delete.failed': '그룹 삭제에 실패했습니다',
    'group.manage.create.failed': '그룹 생성에 실패했습니다',
    'group.manage.create.validation': '그룹 이름과 최소 1개의 기억을 선택해주세요',
    'group.manage.color.orange': '주황',
    'group.manage.color.indigo': '인디고',
    'group.manage.aiTag': 'AI 생성',
    'group.manage.memoriesCount': '{count}개 기억',

    // Withdrawal
    'common.confirmWithdraw': '정말로 계정을 탈퇴하시겠습니까? 모든 데이터가 영구적으로 삭제됩니다.',
    'common.withdrawSuccess': '계정 및 모든 데이터가 안전하게 삭제되었습니다.',
    'common.withdrawFailed': '계정 탈퇴 처리 중 오류가 발생했습니다.',
    'settings.danger.title': '위험 지역',
    'settings.danger.withdraw.title': '계정 탈퇴',
    'settings.danger.withdraw.desc': '서버에 저장된 귀하의 계정 정보와 모든 데이터를 영구적으로 삭제합니다. 이 작업은 되돌릴 수 없습니다.',
    'settings.danger.withdraw.button': '계정 및 데이터 탈퇴',

    // MemoryInput
    'memory.input.guide.widgets': '위젯 가이드',
    'memory.input.guide.widgets.calendar': '캘린더: 날짜 기반 일정 관리',
    'memory.input.guide.widgets.minimap': '미니맵: 보드 전체 뷰',
    'memory.input.guide.widgets.viewer': '뷰어: PDF/이미지 표시',
    'memory.input.guide.widgets.db': '데이터베이스: 테이블 뷰',
    'memory.input.guide.widgets.recorder': '회의록: 실시간 녹음',
    'memory.input.guide.cards': '카드 가이드',
    'memory.input.guide.cards.link': '카드 연결로 관계 시각화',
    'memory.input.guide.cards.flag': '깃발로 북마크 저장',
    'memory.input.guide.cards.group': '그룹으로 분류 정리',
    'memory.input.guide.ai': 'AI 분석 가이드',
    'memory.input.guide.ai.blob': '3개 이상 연결된 카드 그룹에 자동으로 블롭 배경 생성',
    'memory.input.guide.ai.plan': '선택한 카드들을 AI가 분석해 실행 가능한 계획 생성',
    'memory.input.guide.tips': '빠른 시작 팁',
    'memory.input.guide.tips.1': '하단 입력창에 자유롭게 기록하세요.',
    'memory.input.guide.tips.2': '@를 입력해 다른 기록을 멘션하세요.',
    'memory.input.guide.tips.3': '이미지나 PDF를 드래그해서 넣으세요.',
    'memory.input.placeholder.title': '제목 (선택)',
    'memory.input.placeholder.content': '새로운 생각을 기록하세요...',
    'memory.input.button.record': '기록하기',
    'memory.input.button.saving': '...',
    'memory.input.dropzone': '파일을 놓으세요',
    'memory.input.toast.saved': '기억이 저장되었습니다!',
    'memory.input.toast.saveFailed': '기억 저장에 실패했습니다',
    'memory.input.mention.placeholder': '기억 검색...',
    'memory.input.mention.noResult': '결과 없음',
    'memory.input.ai.suggestion.title': '이런 건 어때요?',
    'memory.input.ai.suggestion.close': '닫기',
    'memory.input.link.suggestion.title': '기록 연결 제안',
    'memory.input.link.suggestion.desc': 'AI가 찾은 관련 기록들입니다. 원하는 것만 선택하세요.',
    'memory.input.link.suggestion.skip': '건너뛰기',
    'memory.input.link.suggestion.connect': '연결하기',
    'memory.input.voice.error': '마이크 권한이 필요합니다. 브라우저 설정에서 마이크 권한을 허용해주세요.',
    'memory.input.voice.failed': '음성을 텍스트로 변환하지 못했습니다.',

    // MemoryCard
    'memory.card.action.autoGroup': 'AI로 자동 묶기',
    'memory.card.action.edit': '수정',
    'memory.card.action.save': '저장',
    'memory.card.action.delete': '삭제',
    'memory.card.action.more': '더보기',
    'memory.card.action.fold': '접기',
    'memory.card.ai.summarize': '요약',
    'memory.card.ai.summarize.off': '요약 끄기',
    'memory.card.ai.summarizing': '생성중',
    'memory.card.ai.suggest': '제안',
    'memory.card.ai.suggest.off': '제안 끄기',
    'memory.card.ai.suggesting': '생성중',
    'memory.card.ai.summary.title': 'AI 요약',
    'memory.card.ai.nextSteps.title': '다음 단계',
    'memory.card.ai.resources.title': '관련 자료',
    'memory.card.ai.actionPlan.title': '실행 계획',
    'memory.card.ai.convertToGoal': '🎯 목표로 전환',
    'memory.card.ai.convertToGoal.confirm': '이 AI 제안을 목표로 전환하시겠습니까?',
    'memory.card.ai.convertToGoal.success': '✅ 목표가 생성되었습니다!',
    'memory.card.attachment.download': '다운로드',
    'memory.card.attachment.open': '열기',
    'memory.card.attachment.viewInViewer': 'Viewer에서 보기',
    'memory.card.related.title': '연결된 기록',
    'memory.card.related.add': '+ 추가',
    'memory.card.related.none': '아직 연결된 기록이 없습니다',
    'memory.card.related.more': '{count}개 더',
    'memory.card.related.unlink': '연결 끊기',
    'memory.card.source.gmail': 'Gmail 출처',
    'memory.card.source.ios': 'iOS Shortcut',
    'memory.card.source.quickAdd': 'Quick Add',
    'memory.card.source.openOriginal': '메일 원본 보기',
    'memory.card.source.openLink': '링크 열기',
    'memory.card.edit.failed': '수정에 실패했습니다',
    'memory.card.action.card': '카드',

    // Persona
    'persona.selector.title': '페르소나 선택',
    'persona.selector.desc': 'AI가 당신의 역할에 맞춰 분석합니다',
    'persona.selector.default': '기본 모드',
    'persona.selector.default.desc': '페르소나 없이 사용',
    'persona.selector.create': '새 페르소나 만들기',
    'persona.selector.modal.icon': '아이콘',
    'persona.selector.modal.icon.manual': '또는 직접 입력',
    'persona.selector.modal.name': '이름 *',
    'persona.selector.modal.name.placeholder': 'HR 전문가',
    'persona.selector.modal.desc': '설명',
    'persona.selector.modal.desc.placeholder': '채용, 인사, 조직 관리',
    'persona.selector.modal.context': 'AI 컨텍스트 (역할/관심사)',
    'persona.selector.modal.context.placeholder': 'HR 업무에 관심 많음. 채용 프로세스 개선, 조직 문화, 성과 관리 등에 대해 공부 중.',
    'persona.selector.modal.button.create': '만들기',
    'persona.selector.delete.confirm': '이 페르소나를 삭제하시겠습니까?',

    // Common
    'common.backToHome': '홈으로 돌아가기',
    'common.cancel': '취소',
    'common.close': '닫기',
    'common.delete': '삭제',
    'common.add': '추가',
    'common.note': '메모',
    'common.confirmDeleteMemory': '기억을 삭제하시겠습니까?',
    'common.confirmDeleteWidget': '위젯을 삭제하시겠습니까?',
    'common.deleteFailed': '삭제 실패',
    'common.deleteError': '삭제 중 오류 발생',
    'common.lastUpdated': '최종 업데이트:',

    // Terms & Privacy Page Headings
    'terms.title': '서비스 약관',
    'privacy.title': '개인정보처리방침',

    // Features Page
    'features.header.back': '대시보드로 돌아가기',
    'features.nav.prev': '이전',
    'features.nav.next': '다음',
    'features.nav.keyboard': '키보드 방향키 ← → 로 이동할 수 있습니다',
    
    // Feature 1: Memory Management
    'features.memory.title': '기억 관리',
    'features.memory.subtitle': 'Memory Management',
    'features.memory.desc': '생각의 조각들을 자유롭게 기록하고 저장하세요',
    'features.memory.detail1': '빠른 메모 입력으로 생각을 즉시 캡처',
    'features.memory.detail2': '텍스트, 음성, 파일 등 다양한 형식 지원',
    'features.memory.detail3': '자동 타임스탬프로 시간 흐름 추적',
    'features.memory.detail4': '태그와 그룹으로 체계적 정리',
    
    // Feature 2: Infinite Canvas
    'features.canvas.title': '무한 캔버스',
    'features.canvas.subtitle': 'Infinite Canvas',
    'features.canvas.desc': '공간의 제약 없이 아이디어를 배치하고 연결하세요',
    'features.canvas.detail1': '드래그 앤 드롭으로 자유로운 배치',
    'features.canvas.detail2': '줌인/줌아웃으로 큰 그림 파악',
    'features.canvas.detail3': '연결선으로 관계 시각화',
    'features.canvas.detail4': '미니맵으로 전체 구조 한눈에 보기',
    
    // Feature 3: Smart Grouping
    'features.grouping.title': 'AI 스마트 그룹화',
    'features.grouping.subtitle': 'Smart Grouping',
    'features.grouping.desc': '관련된 기억들을 묶어 맥락을 구체화하세요',
    'features.grouping.detail1': 'AI 기반 자동 그룹 제안',
    'features.grouping.detail2': '컬러 코딩으로 시각적 구분',
    'features.grouping.detail3': '그룹별 필터링과 전역 검색',
    'features.grouping.detail4': '계층 구조로 복잡한 프로젝트 관리',
    
    // Feature 4: AI Insights
    'features.insights.title': 'AI 인사이트',
    'features.insights.subtitle': 'AI Insights',
    'features.insights.desc': '축적된 기억에서 패턴과 인사이트를 발견하세요',
    'features.insights.detail1': '자주 등장하는 주제 자동 추출',
    'features.insights.detail2': '관련 기억 스마트 연결',
    'features.insights.detail3': '생산성 패턴 분석',
    'features.insights.detail4': '개인화된 제안과 리마인더',
    
    // Feature 5: Local-First
    'features.localfirst.title': '로컬 우선',
    'features.localfirst.subtitle': 'Local-First',
    'features.localfirst.desc': '오프라인에서도 완벽하게 작동하는 진정한 개인 공간',
    'features.localfirst.detail1': '인터넷 없이도 모든 기능 사용 가능',
    'features.localfirst.detail2': 'IndexedDB 기반 로컬 저장소',
    'features.localfirst.detail3': '수동/자동 동기화를 선택하여 데이터 안전 보장',
    'features.localfirst.detail4': '프라이버시 완벽 보호',
    
    // Feature 6: Voice Recording
    'features.voice.title': '음성 녹음',
    'features.voice.subtitle': 'Voice Recording',
    'features.voice.desc': '말로 생각을 기록하고 자동으로 텍스트로 변환',
    'features.voice.detail1': '실시간 음성-텍스트 변환',
    'features.voice.detail2': '고품질 음성 파일 저장',
    'features.voice.detail3': '회의록 자동 생성',
    'features.voice.detail4': '다국어 지원',
    
    // Feature 7: File Integration
    'features.files.title': '파일 통합',
    'features.files.subtitle': 'File Integration',
    'features.files.desc': 'PDF, 이미지, 문서를 하나의 공간에서 관리',
    'features.files.detail1': 'PDF 자동 텍스트 추출',
    'features.files.detail2': '이미지 OCR 텍스트 인식',
    'features.files.detail3': '문서 내용 검색 가능',
    'features.files.detail4': '클라우드 스토리지 연동',
    
    // Feature 8: Widgets
    'features.widgets.title': '여러가지 위젯들',
    'features.widgets.subtitle': 'Various Widgets',
    'features.widgets.desc': '캔버스에 추가할 수 있는 다양한 위젯으로 생산성 향상',
    'features.widgets.detail1': '캘린더 위젯으로 일정 관리',
    'features.widgets.detail2': '액션 플랜 위젯으로 진행 상황 추적',
    'features.widgets.detail3': '데이터베이스 위젯으로 정보를 표 형태로 체계적 관리',
    'features.widgets.detail4': '깃발 위젯으로 메모 분류 및 중요 항목 표시',
    
    // Visual Elements - Default Cards
    'features.visual.card.summary': '요약',
    'features.visual.card.suggestion': '제안',
    'features.visual.card.tag.memo': '@빠른메모',
    'features.visual.card.tag.memo.desc': ' 입력으로 생각을 즉시 캡처',
    'features.visual.card.tag1': '프로젝트',
    'features.visual.card.tag2': '아이디어',

    // Visual Elements - Canvas Slide
    'features.visual.canvas.card1.title': '프로젝트 아이디어',
    'features.visual.canvas.card1.desc': '무한 캔버스에서 자유롭게 생각을 배치하고 연결할 수 있습니다',
    'features.visual.canvas.card2.title': '다음 단계',
    'features.visual.canvas.card2.desc': '드래그로 카드 위치를 자유롭게 조정하세요',
    'features.visual.canvas.card3.title': '회의 노트',
    'features.visual.canvas.card3.desc': '관련된 카드들을 가까이 배치하여 연결하세요',
    'features.visual.canvas.calendar': '2026년 2월',
    'features.visual.canvas.days': ['일', '월', '화', '수', '목', '금', '토'],
    'features.visual.time.justnow': '방금 전',
    'features.visual.time.min5': '5분 전',
    'features.visual.time.min10': '10분 전',
    
    // Visual Elements - Grouping Slide
    'features.visual.grouping.card.title': '이직 면접 준비',
    'features.visual.grouping.card.desc': '면접에서 자주 묻는 질문들을 정리하고 답변을 준비해야 합니다.',
    'features.visual.grouping.modal.title': '이렇게 묶을까요?',
    'features.visual.grouping.modal.subtitle': '묶일 기록들 (2개)',
    'features.visual.grouping.modal.card1': '이직 면접 준비',
    'features.visual.grouping.modal.card1desc': '면접에서 자주 묻는 질문들...',
    'features.visual.grouping.modal.card2': 'STAR 기법 정리',
    'features.visual.grouping.modal.card2desc': '경험을 구조화하는 방법...',
    'features.visual.grouping.modal.groupname': '취업 준비',
    'features.visual.grouping.modal.cancel': '취소',
    'features.visual.grouping.modal.submit': '묶기',
    'features.visual.grouping.modal.aitext': 'AI가 자동으로\n관련 기록 제안',
    'features.visual.grouping.aibtn': 'AI 자동 묶기',
    
    // Visual Elements - Insights Slide
    'features.visual.insights.title': '데일리 정리 시간',
    'features.visual.insights.desc': '오늘 하루를 돌아보고\n내일을 준비해요',
    'features.visual.insights.date': '2월 16일 (월)',
    'features.visual.insights.mode': '기본 모드',
    'features.visual.insights.refresh': '새로고침',
    'features.visual.insights.summary.title': '요약',
    'features.visual.insights.summary.content': '사용자는 최근 이직 면접 준비와 관련된 자료에 많은 관심을 보이고 있으며, 경력 및 경험을 효과적으로 정리하는 데 중점을 두고 있습니다. 특히, 면접 질문과 답변 전략을 고민하고 있으며, 이를 통해 성공적인 이직을 목표로 하고 있습니다.',
    'features.visual.insights.suggestions.title': '제안',
    'features.visual.insights.suggestions.1': '면접 준비를 위해 모의 면접을 진행하여 실전 감각을 익혀보세요.',
    'features.visual.insights.suggestions.2': '자신의 경험을 체계적으로 정리하고, 면접에서의 답변 전략을 고민해보는 것이 도움이 될 겁니다.',
    
    // Visual Elements - Voice Recording Slide
    'features.visual.voice.title': '미팅 레코더',
    'features.visual.voice.recording': '녹음 중',
    'features.visual.voice.pause': '일시정지',
    'features.visual.voice.speaker1': '김민수',
    'features.visual.voice.speaker2': '이지원',
    'features.visual.voice.speaker3': '박서준',
    'features.visual.voice.line1': '네, 그럼 이번 프로젝트의 주요 일정에 대해서 논의해볼까요?',
    'features.visual.voice.line2': '좋습니다. 먼저 1차 베타 테스트는 다음 주 금요일까지 완료하는 것으로 하고요.',
    'features.visual.voice.line3': 'UI 디자인은 이번 주 안에 마무리할 수 있을 것 같습니다.',
    'features.visual.voice.line4': '좋네요. 그럼 개발 일정도 조정해서...',
    
    // Visual Elements - Widgets Slide
    'features.visual.widgets.action.label': '액션 프로젝트',
    'features.visual.widgets.action.duration': '약 3주',
    'features.visual.widgets.action.title': '신규 프로젝트 기획',
    'features.visual.widgets.action.summary': '"시장 조사부터 베타 테스트까지 체계적으로 진행하여 성공적인 프로젝트 런칭을 목표로 합니다."',
    'features.visual.widgets.action.step': '[1단계: 시장 조사]',
    'features.visual.widgets.action.task': '경쟁사 분석 및 시장 동향 파악',
    'features.visual.widgets.table.title': '팀원 관리',
    'features.visual.widgets.table.rows': '(3개 행)',
    'features.visual.widgets.table.name': '이름',
    'features.visual.widgets.table.role': '역할',
    'features.visual.widgets.table.status': '상태',
    'features.visual.widgets.table.progress': '진행률',
    'features.visual.widgets.table.role1': '개발자',
    'features.visual.widgets.table.role2': '디자이너',
    'features.visual.widgets.table.role3': '기획자',
    'features.visual.widgets.table.status1': '진행중',
    'features.visual.widgets.table.status2': '완료',
    'features.visual.widgets.table.status3': '대기',
    
    // Visual Elements - Local First Slide  
    'features.visual.localfirst.local': '로컬 저장소',
    'features.visual.localfirst.indexeddb': 'IndexedDB',
    'features.visual.localfirst.offline': '오프라인 작동',
    'features.visual.localfirst.cloud': '클라우드',
    'features.visual.localfirst.backup': '백업 & 동기화',
    'features.visual.localfirst.safe': '안전한 보관',
    'features.visual.localfirst.sync': '자동 동기화',
    'features.visual.localfirst.infotext': '인터넷 연결 없이도 작동',
    'features.visual.localfirst.infodesc': '모든 데이터가 로컬에 저장되어 오프라인에서도 작업 가능. 온라인 시 자동 동기화',
  },
  en: {
    // Landing
    'landing.title': 'WORKLESS',
    'landing.subtitle': 'Unstructured Agile Workspace',
    'landing.mainText': 'For Your Action!',
    'landing.feature1.title': 'AI & Integration',
    'landing.feature1.gmail.title': 'Gmail Integration',
    'landing.feature1.gmail.desc': 'Automatically convert emails with "Workless" label into memory cards',
    'landing.feature1.ai.title': 'AI Assistant',
    'landing.feature1.ai.desc': 'Understand context, suggest insights & action items, and auto-link related information',
    'landing.feature2.title': 'Core Features',
    'landing.feature2.canvas.title': 'Infinite Canvas Whiteboard',
    'landing.feature2.canvas.desc': 'A productivity tool to freely note ideas, brainstorm, and organize systematically in an endless 2D space',
    'landing.feature3.title': 'AI Persona Customization',
    'landing.feature3.desc': 'Create an AI assistant that fits your work style. From friendly coaches to professional consultants and creative partners - maximize productivity with your own customized AI collaboration tool.',
    'landing.feature4.title': 'Widgets & Visualization',
    'landing.feature4.widgets.title': 'Various Widget Tools',
    'landing.feature4.widgets.desc': 'Expand your whiteboard into a professional workspace with practical widgets like calendar, doc viewer, todo, and minimap',
    'landing.feature4.viz.title': 'Knowledge Context Visualization',
    'landing.feature4.viz.desc': 'Memos and ideas linked by tags are automatically grouped, allowing you to intuitively grasp thought flows and relationships through spatial placement',
    'landing.start': 'Get Started',
    'landing.agree': 'I agree to the Terms of Service and Privacy Policy',
    'landing.terms': 'Terms of Service',
    'landing.privacy': 'Privacy Policy',
    'landing.gmail.title': 'Gmail Data Usage:',
    'landing.gmail.desc': 'We only access emails with the "Workless" label in read-only mode to convert them into memos. We do not send or modify emails.',
    'landing.privacy.title': 'Privacy:',
    'landing.privacy.desc': 'Collected data is used solely for service provision and is never sold to third parties.',
    'landing.contact': 'Contact Us',

    // Gmail Import
    'gmail.import.title': 'Select Gmail Messages',
    'gmail.import.desc': 'Please select messages to import (Label: Workless)',
    'gmail.import.empty': 'No messages available to import.',
    'gmail.import.alreadyImported': 'Already added',
    'gmail.import.button.cancel': 'Cancel',
    'gmail.import.button.import': 'Import {count} messages',
    'gmail.import.toast.analyzing': 'Analyzing messages...',
    'gmail.import.toast.converting': 'AI is converting messages to records...',
    'gmail.import.noNewMail': 'No new mail',
    'gmail.import.checking': 'Checking...',
    'gmail.import.importing': 'Importing...',
    'gmail.import.selecting': 'Selecting...',
    'gmail.import.failed': 'Failed',

    // Onboarding
    'onboarding.note': 'Create Note',
    'onboarding.note.desc1': '• Attach files',
    'onboarding.note.desc2': '• Ref via @tags',
    'onboarding.connect': 'Connect Cards',
    'onboarding.connect.desc1': '• Link cards with lines',
    'onboarding.connect.desc2': '• AI auto-group suggestions',
    'onboarding.tag': 'Tags & Sorting',
    'onboarding.tag.desc1': '• Auto-tagging',
    'onboarding.tag.desc2': '• Time context tracking',
    'onboarding.action': 'Get Started',
    'onboarding.progress': 'PROGRESS',
    'onboarding.todo1': 'Create 3 cards',
    'onboarding.todo2': 'Connect cards',
    'onboarding.todo3': 'Try AI features',
    'onboarding.calendar': 'Calendar',
    'onboarding.preview': 'PREVIEW',
    'onboarding.justNow': 'Just now',
    'onboarding.tutorial': 'Tutorial',
    'onboarding.feature': 'Feature',

    // Dashboard
    'dashboard.title': 'Workless',
    'dashboard.subtitle': 'Unstructured workspace for flow of thought',
    'dashboard.menu.groups': 'Manage Groups',
    'dashboard.menu.memories': 'Manage Memories',
    'dashboard.menu.settings': 'Settings',
    'dashboard.auth.logout': 'Logout',
    'dashboard.auth.login': 'Login',
    'dashboard.loading.workspace': 'Loading workspace...',
    'dashboard.loading.redirecting': 'Redirecting to login...',
    'dashboard.loading.fetching': 'Fetching...',
    'dashboard.insights.show': 'Show Insights',
    'dashboard.insights.hide': 'Hide Insights',
    'dashboard.modal.groups.title': 'Manage Groups',
    'dashboard.modal.query.title': 'Ask AI',

    // MemoryListPanel
    'memory.list.title': 'Manage Memories',
    'memory.list.tab.all': 'All ({count})',
    'memory.list.tab.memory': 'Memories ({count})',
    'memory.list.tab.widget': 'Widgets ({count})',
    'memory.list.search.placeholder': 'Search...',
    'memory.list.noResult': 'No items found',
    'memory.list.item.noTitle': 'No Title',
    'memory.list.project.title': 'Action Project',
    'memory.list.project.estimated': 'Est: {duration}',
    'project.draft.button': 'Draft',
    'project.draft.generating': 'Generating...',

    // MemoryView
    'memory.view.button.board': 'Go to Board',
    'memory.view.mode.board': 'Board View',
    'memory.view.mode.list': 'List View',
    'memory.view.recent': 'Recent Memories',
    'memory.view.noMemory': 'No memories saved yet. Record your first thought in the input below!',
    'memory.view.zoom': 'Zoom',
    'memory.view.loading': 'Loading...',
    'memory.view.ai.analyzing': 'AI is analyzing the group...',
    'memory.view.ai.failed': 'Could not load group description.',
    'memory.view.board.title': 'Whiteboard',
    'memory.view.board.restore': 'Restore Layout',
    'memory.view.board.restore.title': 'Restore to previous layout',
    'memory.view.board.arrange': 'Auto Arrange',
    'memory.view.board.arrange.title': 'Auto arrange based on connections',
    'memory.view.board.arranging': 'Arranging...',
    'memory.view.board.import.gmail': 'Import Gmail',
    'memory.view.board.import.gmail.success': 'Imported {count} emails from Gmail.',
    'memory.view.board.widget.add': 'Add Widget',
    'memory.view.board.widget.menu': 'Widgets',
    'memory.view.board.widget.synergy': 'Widget Synergy',
    'memory.view.board.group.manage': 'Manage Groups',
    'memory.view.board.group': 'Group',
    'memory.view.board.flag.manage': 'Manage Flags',
    'memory.view.board.flag': 'Flag',
    'memory.view.board.zoom.reset': 'Reset',
    'memory.view.board.widget.minimap': 'Minimap',
    'memory.view.board.widget.viewer': 'Viewer',
    'memory.view.board.widget.recorder': 'Recorder',
    'memory.view.board.widget.db': 'DB',
    'memory.view.board.widget.actionPlan': 'Action Plan',
    'memory.view.board.widget.blob': 'Blob',
    'memory.view.board.widget.blob.on': 'Blob ON',
    'memory.view.board.widget.minimap.limit': 'Only one minimap per board',
    'memory.view.board.widget.actionPlan.select': 'Select memories first',

    // Calendar
    'calendar.title': 'Calendar',
    'calendar.view.month': 'Month',
    'calendar.view.week': 'Week',
    'calendar.view.day': 'Day',
    'calendar.view.week.empty': 'Week view is coming soon',
    'calendar.record.count': '{count} records',
    'calendar.todo.count': '{count} todos',
    'calendar.todo.title': 'Schedule',
    'calendar.todo.add': '+ Add',
    'calendar.todo.placeholder': 'Enter schedule... (use @ to tag)',
    'calendar.todo.none': 'No schedule',
    'calendar.memory.title': 'Records',
    'calendar.memory.none': 'No records for this day',
    'calendar.back': 'Back',
    'calendar.format.month': 'MMMM yyyy',
    'calendar.format.day': 'EEEE, MMMM d, yyyy',

    // InsightsPanel
    'insights.title': 'Daily Review',
    'insights.desc': 'Review your day\nPrepare for tomorrow',
    'insights.refresh': 'Refresh',
    'insights.summary.title': 'Summary',
    'insights.goals.title': '🎯 Ongoing Goals',
    'insights.goals.progress': 'Progress',
    'insights.goals.completed': '{completed}/{total} steps completed',
    'insights.topics.title': 'Key Topics',
    'insights.topics.count': '{count}',
    'insights.suggestions.title': 'Suggestions',
    'insights.loading': 'Analyzing...',
    'insights.error': 'Could not load insights',
    'insights.error.title': 'Error',
    'insights.error.retry': 'Retry',
    'insights.goal.category.idea': 'Idea',
    'insights.goal.category.request': 'Request',
    'insights.goal.category.habit': 'Habit',
    'insights.goal.modal.desc': '📝 Goal Description',
    'insights.goal.modal.plan': 'Action Plan',
    'insights.goal.modal.progress': 'Total Progress',
    'insights.goal.modal.created': 'Created on {date}',
    'insights.goal.action.archive': 'Archive',
    'insights.goal.action.delete': 'Delete',
    'insights.goal.action.save': 'Save',
    'insights.goal.action.saving': 'Saving...',
    'insights.goal.toast.updated': '✅ Goal updated!',
    'insights.goal.toast.deleted': '✅ Goal deleted!',
    'insights.goal.toast.archived': '✅ Goal archived!',
    'insights.goal.toast.updateFailed': 'Update failed',
    'insights.goal.toast.updateError': 'Error occurred during update',
    'insights.goal.toast.archiveFailed': 'Archive failed',
    'insights.goal.toast.archiveError': 'Error occurred during archiving',

    // Settings
    'settings.title': 'Data & Sync Settings',
    'settings.desc': 'Workless prioritizes saving data in your browser, working even offline.',
    'settings.status.title': 'System Status',
    'settings.status.network': 'Network Status',
    'settings.status.online': 'Online (Connected)',
    'settings.status.offline': 'Offline',
    'settings.status.syncMode': 'Current Sync Mode',
    'settings.status.syncMode.disabled': 'Cloud Sync Disabled',
    'settings.status.syncMode.enabled': 'Waiting for Manual Sync',
    'settings.status.syncMode.auto': 'Automatic Real-time Sync',
    'settings.status.lastSync': 'Last Synced',
    'settings.status.needsSync': 'You have unsynced data.',
    'settings.status.stats.title': 'Local Device Stats',
    'settings.status.stats.memories': 'Memories',
    'settings.status.stats.groups': 'Groups',
    'settings.status.stats.goals': 'Goals',
    'settings.status.stats.widgets': 'Widgets',
    'settings.sync.title': 'Sync Options',
    'settings.sync.disabled.title': 'Cloud Disabled (Local Only)',
    'settings.sync.disabled.desc': 'No data is sent to the server. Your privacy is fully protected, but you cannot see your data on other devices.',
    'settings.sync.manual.title': 'Manual Backup Mode',
    'settings.sync.manual.desc': 'Data stays on your device, and you backup to the server only when you click the "Sync Now" button.',
    'settings.sync.auto.title': 'Real-time Sync (Recommended)',
    'settings.sync.auto.desc': 'Data syncs automatically whenever changes occur. Access the same content instantly on mobile or other computers.',
    'settings.sync.encryption.title': 'End-to-End Encryption',
    'settings.sync.encryption.desc': 'Data sent to the server is encrypted using AES-256. No one can access the content without the key generated from your password.',
    'settings.sync.button.backup': 'Backup to Server Now',
    'settings.sync.button.backup.progress': 'Syncing...',
    'settings.sync.button.restore': 'Restore from Server',
    'settings.sync.button.diagnose': 'Diagnose Local Data',
    'settings.sync.button.forceRestore': 'Can\'t see your data? Force restore from server',
    'settings.export.title': 'Export & Import Data',
    'settings.export.section.title': 'Export',
    'settings.export.section.desc': 'Download all data stored in the browser as a JSON file. Use this if you want to manage your backups manually.',
    'settings.export.button': '📥 Download Data File',
    'settings.import.section.title': 'Import',
    'settings.import.section.desc': 'Load a previously exported JSON file.',
    'settings.import.placeholder': 'Select a JSON file or drag it here',
    'settings.import.button.overwrite': 'Overwrite All',
    'settings.import.button.merge': 'Merge with Existing Data',
    'settings.info.title': 'About Local-First Technology',
    'settings.info.1': 'Your data is primarily recorded in a secure storage called IndexedDB in your browser.',
    'settings.info.2': 'Even without network, you can use all features like adding or searching memos.',
    'settings.info.3': 'Server sync is optional for backup and multi-device support.',
    'settings.info.4': 'We follow the philosophy that "Your data should stay on your device."',
    'settings.button.back': 'Back to Dashboard',
    'settings.auth.required': 'Login required.',
    'settings.auth.button': 'Go to Login',

    // QueryPanel
    'query.placeholder': 'e.g. What have I been thinking about lately?',
    'query.button.ask': 'Ask',
    'query.button.thinking': 'Thinking...',
    'query.quick.1': 'What have I been thinking about lately?',
    'query.quick.2': 'What ideas have I collected?',
    'query.quick.3': 'Show work-related records',
    'query.quick.4': 'Summarize recent minutes',
    'query.result.summary': 'Summary',
    'query.result.related': 'Related Memories ({count})',
    'query.result.suggestions': 'Suggestions',
    'query.error.failed': 'Failed to generate summary',

    // Auth
    'auth.signin.title': 'WORKLESS',
    'auth.signin.subtitle': 'Unstructured Agile Workspace',
    'auth.signin.desc': 'Sign in with your Google account to get started',
    'auth.signin.button': 'Sign in with Google',
    'auth.signin.guide.title': 'How to use 👇',
    'auth.signin.guide.desc': 'Start immediately after logging in',
    'auth.signin.alert.terms': 'You must agree to the Terms of Service.',

    // GlobalSearch
    'search.placeholder': 'Press / to search memories...',
    'search.guide.move': 'Move',
    'search.guide.select': 'Select',
    'search.guide.close': 'Close',
    'search.noResult': 'No results found',

    // Flag Management
    'flag.manage.add': 'Add Flag',
    'flag.manage.placing': '📍 Click on the board to place a flag (ESC: Cancel)',
    'flag.manage.noFlags': 'Add flags to bookmark important locations',

    // Group Management
    'group.manage.all': 'All',
    'group.manage.title': 'Manage Groups',
    'group.manage.desc': 'Organize related memories into groups',
    'group.manage.button.ai': 'Group with AI',
    'group.manage.button.create': 'Create Manually',
    'group.manage.noGroups': 'No groups yet',
    'group.manage.ai.title': 'AI Group Suggestions',
    'group.manage.ai.accept': 'Create',
    'group.manage.modal.create.title': 'Create New Group',
    'group.manage.modal.create.name': 'Group Name',
    'group.manage.modal.create.name.placeholder': 'e.g., Project Ideas',
    'group.manage.modal.create.color': 'Color',
    'group.manage.modal.create.memories': 'Select Memories ({count})',
    'group.manage.modal.create.button.create': 'Create',
    'group.manage.toast.ai.analyzing': 'AI is analyzing your memories...',
    'group.manage.toast.ai.failed': 'Failed to get AI suggestions',
    'group.manage.delete.confirm': 'Are you sure you want to delete this group?',
    'group.manage.delete.failed': 'Failed to delete group',
    'group.manage.create.failed': 'Failed to create group',
    'group.manage.create.validation': 'Please enter a group name and select at least one memory',
    'group.manage.color.orange': 'Orange',
    'group.manage.color.indigo': 'Indigo',
    'group.manage.aiTag': 'AI Generated',
    'group.manage.memoriesCount': '{count} memories',

    // Withdrawal
    'common.confirmWithdraw': 'Are you sure you want to delete your account? All your data will be permanently removed.',
    'common.withdrawSuccess': 'Your account and data have been safely deleted.',
    'common.withdrawFailed': 'Failed to delete account.',
    'settings.danger.title': 'Danger Zone',
    'settings.danger.withdraw.title': 'Delete Account',
    'settings.danger.withdraw.desc': 'Permanently delete your account and all associated data from the server. This action cannot be undone.',
    'settings.danger.withdraw.button': 'Delete My Account',

    // MemoryInput
    'memory.input.guide.widgets': 'Widget Guide',
    'memory.input.guide.widgets.calendar': 'Calendar: Date-based scheduling',
    'memory.input.guide.widgets.minimap': 'Minimap: Full board view',
    'memory.input.guide.widgets.viewer': 'Viewer: Display PDF/Images',
    'memory.input.guide.widgets.db': 'Database: Table view',
    'memory.input.guide.widgets.recorder': 'Minutes: Real-time recording',
    'memory.input.guide.cards': 'Card Guide',
    'memory.input.guide.cards.link': 'Visualize relations via links',
    'memory.input.guide.cards.flag': 'Save bookmarks with flags',
    'memory.input.guide.cards.group': 'Organize with groups',
    'memory.input.guide.ai': 'AI Analysis Guide',
    'memory.input.guide.ai.blob': 'Auto-blob background for 3+ linked cards',
    'memory.input.guide.ai.plan': 'AI analyzes cards to create actionable plans',
    'memory.input.guide.tips': 'Quick Start Tips',
    'memory.input.guide.tips.1': 'Note down thoughts in the input below.',
    'memory.input.guide.tips.2': 'Type @ to mention other notes.',
    'memory.input.guide.tips.3': 'Drag & drop images or PDFs.',
    'memory.input.placeholder.title': 'Title (Optional)',
    'memory.input.placeholder.content': 'Note down your thoughts...',
    'memory.input.button.record': 'Record',
    'memory.input.button.saving': '...',
    'memory.input.dropzone': 'Drop files here',
    'memory.input.toast.saved': 'Memory saved!',
    'memory.input.toast.saveFailed': 'Failed to save memory',
    'memory.input.mention.placeholder': 'Search memories...',
    'memory.input.mention.noResult': 'No results',
    'memory.input.ai.suggestion.title': 'How about this?',
    'memory.input.ai.suggestion.close': 'Close',
    'memory.input.link.suggestion.title': 'Record Link Suggestions',
    'memory.input.link.suggestion.desc': 'AI found related records. Select the ones you want.',
    'memory.input.link.suggestion.skip': 'Skip',
    'memory.input.link.suggestion.connect': 'Connect',
    'memory.input.voice.error': 'Microphone permission required. Please allow it in browser settings.',
    'memory.input.voice.failed': 'Failed to transcribe voice to text.',

    // MemoryCard
    'memory.card.action.autoGroup': 'AI Auto Group',
    'memory.card.action.edit': 'Edit',
    'memory.card.action.save': 'Save',
    'memory.card.action.delete': 'Delete',
    'memory.card.action.more': 'More',
    'memory.card.action.fold': 'Fold',
    'memory.card.ai.summarize': 'Summarize',
    'memory.card.ai.summarize.off': 'Turn off summary',
    'memory.card.ai.summarizing': 'Generating...',
    'memory.card.ai.suggest': 'Suggest',
    'memory.card.ai.suggest.off': 'Turn off suggestions',
    'memory.card.ai.suggesting': 'Generating...',
    'memory.card.ai.summary.title': 'AI Summary',
    'memory.card.ai.nextSteps.title': 'Next Steps',
    'memory.card.ai.resources.title': 'Related Resources',
    'memory.card.ai.actionPlan.title': 'Action Plan',
    'memory.card.ai.convertToGoal': '🎯 Convert to Goal',
    'memory.card.ai.convertToGoal.confirm': 'Convert this AI suggestion to a goal?',
    'memory.card.ai.convertToGoal.success': '✅ Goal created!',
    'memory.card.attachment.download': 'Download',
    'memory.card.attachment.open': 'Open',
    'memory.card.attachment.viewInViewer': 'View in Viewer',
    'memory.card.related.title': 'Linked Records',
    'memory.card.related.add': '+ Add',
    'memory.card.related.none': 'No linked records yet',
    'memory.card.related.more': '+{count} more',
    'memory.card.related.unlink': 'Unlink',
    'memory.card.source.gmail': 'Gmail Source',
    'memory.card.source.ios': 'iOS Shortcut',
    'memory.card.source.quickAdd': 'Quick Add',
    'memory.card.source.openOriginal': 'Open Original Mail',
    'memory.card.source.openLink': 'Open Link',
    'memory.card.edit.failed': 'Failed to edit',
    'memory.card.action.card': 'Card',

    // Persona
    'persona.selector.title': 'Select Persona',
    'persona.selector.desc': 'AI analyzes according to your role',
    'persona.selector.default': 'Default Mode',
    'persona.selector.default.desc': 'Use without persona',
    'persona.selector.create': 'Create New Persona',
    'persona.selector.modal.icon': 'Icon',
    'persona.selector.modal.icon.manual': 'or enter manually',
    'persona.selector.modal.name': 'Name *',
    'persona.selector.modal.name.placeholder': 'HR Expert',
    'persona.selector.modal.desc': 'Description',
    'persona.selector.modal.desc.placeholder': 'Recruitment, HR, Org Management',
    'persona.selector.modal.context': 'AI Context (Role/Interests)',
    'persona.selector.modal.context.placeholder': 'Interested in HR. Studying recruitment process improvement, org culture, performance management, etc.',
    'persona.selector.modal.button.create': 'Create',
    'persona.selector.delete.confirm': 'Are you sure you want to delete this persona?',

    // Common
    'common.backToHome': 'Back to Home',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.note': 'Note',
    'common.confirmDeleteMemory': 'Are you sure you want to delete this memory?',
    'common.confirmDeleteWidget': 'Are you sure you want to delete this widget?',
    'common.deleteFailed': 'Delete failed',
    'common.deleteError': 'Error occurred during deletion',
    'common.lastUpdated': 'Last Updated:',

    // Terms & Privacy Page Headings
    'terms.title': 'Terms of Service',
    'privacy.title': 'Privacy Policy',

    // Features Page
    'features.header.back': 'Back to Dashboard',
    'features.nav.prev': 'Previous',
    'features.nav.next': 'Next',
    'features.nav.keyboard': 'Use arrow keys ← → to navigate',
    
    // Feature 1: Memory Management
    'features.memory.title': 'Memory Management',
    'features.memory.subtitle': 'Memory Management',
    'features.memory.desc': 'Record and save your thoughts freely',
    'features.memory.detail1': 'Capture thoughts instantly with quick memo input',
    'features.memory.detail2': 'Support for various formats: text, voice, files',
    'features.memory.detail3': 'Track time flow with automatic timestamps',
    'features.memory.detail4': 'Organize systematically with tags and groups',
    
    // Feature 2: Infinite Canvas
    'features.canvas.title': 'Infinite Canvas',
    'features.canvas.subtitle': 'Infinite Canvas',
    'features.canvas.desc': 'Place and connect ideas without spatial constraints',
    'features.canvas.detail1': 'Free positioning with drag and drop',
    'features.canvas.detail2': 'See the big picture with zoom in/out',
    'features.canvas.detail3': 'Visualize relationships with connection lines',
    'features.canvas.detail4': 'View entire structure at a glance with minimap',
    
    // Feature 3: Smart Grouping
    'features.grouping.title': 'Smart Grouping',
    'features.grouping.subtitle': 'Smart Grouping',
    'features.grouping.desc': 'Group related memories to clarify context',
    'features.grouping.detail1': 'AI-based automatic group suggestions',
    'features.grouping.detail2': 'Visual distinction with color coding',
    'features.grouping.detail3': 'Filtering and search by group',
    'features.grouping.detail4': 'Manage complex projects with hierarchical structure',
    
    // Feature 4: AI Insights
    'features.insights.title': 'AI Insights',
    'features.insights.subtitle': 'AI Insights',
    'features.insights.desc': 'Discover patterns and insights from accumulated memories',
    'features.insights.detail1': 'Auto-extract frequently appearing topics',
    'features.insights.detail2': 'Smart connection of related memories',
    'features.insights.detail3': 'Productivity pattern analysis',
    'features.insights.detail4': 'Personalized suggestions and reminders',
    
    // Feature 5: Local-First
    'features.localfirst.title': 'Local-First',
    'features.localfirst.subtitle': 'Local-First',
    'features.localfirst.desc': 'A truly personal space that works perfectly offline',
    'features.localfirst.detail1': 'All features available without internet',
    'features.localfirst.detail2': 'IndexedDB-based local storage',
    'features.localfirst.detail3': 'Choose manual/automatic sync to ensure data safety',
    'features.localfirst.detail4': 'Complete privacy protection',
    
    // Feature 6: Voice Recording
    'features.voice.title': 'Voice Recording',
    'features.voice.subtitle': 'Voice Recording',
    'features.voice.desc': 'Record thoughts by voice and auto-convert to text',
    'features.voice.detail1': 'Real-time voice-to-text conversion',
    'features.voice.detail2': 'High-quality audio file storage',
    'features.voice.detail3': 'Automatic meeting minutes generation',
    'features.voice.detail4': 'Multi-language support',
    
    // Feature 7: File Integration
    'features.files.title': 'File Integration',
    'features.files.subtitle': 'File Integration',
    'features.files.desc': 'Manage PDFs, images, and documents in one space',
    'features.files.detail1': 'Automatic PDF text extraction',
    'features.files.detail2': 'Image OCR text recognition',
    'features.files.detail3': 'Searchable document content',
    'features.files.detail4': 'Cloud storage integration',
    
    // Feature 8: Widgets
    'features.widgets.title': 'Various Widgets',
    'features.widgets.subtitle': 'Various Widgets',
    'features.widgets.desc': 'Boost productivity with various widgets for your canvas',
    'features.widgets.detail1': 'Schedule management with calendar widget',
    'features.widgets.detail2': 'Track progress with action plan widget',
    'features.widgets.detail3': 'Manage information in table format with database widget',
    'features.widgets.detail4': 'Classify memos and mark important items with flag widget',
    
    // Visual Elements - Default Cards
    'features.visual.card.summary': 'Summary',
    'features.visual.card.suggestion': 'Suggest',
    'features.visual.card.tag.memo': '@QuickMemo',
    'features.visual.card.tag.memo.desc': ' to capture thoughts instantly',
    'features.visual.card.tag1': 'Project',
    'features.visual.card.tag2': 'Ideas',

    // Visual Elements - Canvas Slide
    'features.visual.canvas.card1.title': 'Project Ideas',
    'features.visual.canvas.card1.desc': 'Freely place and connect thoughts on an infinite canvas',
    'features.visual.canvas.card2.title': 'Next Steps',
    'features.visual.canvas.card2.desc': 'Freely adjust card positions by dragging',
    'features.visual.canvas.card3.title': 'Meeting Notes',
    'features.visual.canvas.card3.desc': 'Place related cards close to connect them',
    'features.visual.canvas.calendar': 'February 2026',
    'features.visual.canvas.days': ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    'features.visual.time.justnow': 'Just now',
    'features.visual.time.min5': '5 min ago',
    'features.visual.time.min10': '10 min ago',
    
    // Visual Elements - Grouping Slide
    'features.visual.grouping.card.title': 'Job Interview Prep',
    'features.visual.grouping.card.desc': 'Organize frequently asked questions and prepare answers.',
    'features.visual.grouping.modal.title': 'Group these together?',
    'features.visual.grouping.modal.subtitle': 'Records to group (2)',
    'features.visual.grouping.modal.card1': 'Job Interview Prep',
    'features.visual.grouping.modal.card1desc': 'Frequently asked questions...',
    'features.visual.grouping.modal.card2': 'STAR Method',
    'features.visual.grouping.modal.card2desc': 'How to structure experiences...',
    'features.visual.grouping.modal.groupname': 'Career Prep',
    'features.visual.grouping.modal.cancel': 'Cancel',
    'features.visual.grouping.modal.submit': 'Group',
    'features.visual.grouping.modal.aitext': 'AI automatically\nsuggests related records',
    'features.visual.grouping.aibtn': 'AI Auto Group',
    
    // Visual Elements - Insights Slide
    'features.visual.insights.title': 'Daily Review Time',
    'features.visual.insights.desc': 'Reflect on today\nand prepare for tomorrow',
    'features.visual.insights.date': 'Feb 16 (Mon)',
    'features.visual.insights.mode': 'Default Mode',
    'features.visual.insights.refresh': 'Refresh',
    'features.visual.insights.summary.title': 'Summary',
    'features.visual.insights.summary.content': 'You have been showing great interest in job interview preparation materials and focusing on effectively organizing your career and experiences. You are particularly thinking about interview questions and answer strategies to achieve a successful career transition.',
    'features.visual.insights.suggestions.title': 'Suggestions',
    'features.visual.insights.suggestions.1': 'Practice with mock interviews to get a feel for real situations.',
    'features.visual.insights.suggestions.2': 'Systematically organize your experiences and consider answer strategies for interviews.',
    
    // Visual Elements - Voice Recording Slide
    'features.visual.voice.title': 'Meeting Recorder',
    'features.visual.voice.recording': 'Recording',
    'features.visual.voice.pause': 'Pause',
    'features.visual.voice.speaker1': 'Alex',
    'features.visual.voice.speaker2': 'Sarah',
    'features.visual.voice.speaker3': 'James',
    'features.visual.voice.line1': 'So, shall we discuss the main schedule for this project?',
    'features.visual.voice.line2': 'Sure. First, let\'s aim to finish the 1st beta test by next Friday.',
    'features.visual.voice.line3': 'I think we can wrap up the UI design within this week.',
    'features.visual.voice.line4': 'Great. Then let\'s adjust the dev schedule too...',
    
    // Visual Elements - Widgets Slide
    'features.visual.widgets.action.label': 'Action Project',
    'features.visual.widgets.action.duration': '~3 weeks',
    'features.visual.widgets.action.title': 'New Project Planning',
    'features.visual.widgets.action.summary': '"Aiming for a successful project launch by systematically progressing from market research to beta testing."',
    'features.visual.widgets.action.step': '[Phase 1: Market Research]',
    'features.visual.widgets.action.task': 'Competitor analysis & market trend research',
    'features.visual.widgets.table.title': 'Team Management',
    'features.visual.widgets.table.rows': '(3 rows)',
    'features.visual.widgets.table.name': 'Name',
    'features.visual.widgets.table.role': 'Role',
    'features.visual.widgets.table.status': 'Status',
    'features.visual.widgets.table.progress': 'Progress',
    'features.visual.widgets.table.role1': 'Developer',
    'features.visual.widgets.table.role2': 'Designer',
    'features.visual.widgets.table.role3': 'Planner',
    'features.visual.widgets.table.status1': 'In Progress',
    'features.visual.widgets.table.status2': 'Done',
    'features.visual.widgets.table.status3': 'Waiting',
    
    // Visual Elements - Local First Slide  
    'features.visual.localfirst.local': 'Local Storage',
    'features.visual.localfirst.indexeddb': 'IndexedDB',
    'features.visual.localfirst.offline': 'Offline Ready',
    'features.visual.localfirst.cloud': 'Cloud',
    'features.visual.localfirst.backup': 'Backup & Sync',
    'features.visual.localfirst.safe': 'Safe Storage',
    'features.visual.localfirst.sync': 'Auto Sync',
    'features.visual.localfirst.infotext': 'Works without internet',
    'features.visual.localfirst.infodesc': 'All data stored locally for offline work. Auto-syncs when online',
  },
};
